### ISSUE TITLE
Support Basic Latin Alphabet

### ISSUE THREAD

**Issue by davelab6** [s-a/digital-numbers-font#1]
The _Basic Latin_ is ~200 glyphs listed in [github.com/google/fonts/tools/encodings/latin_unique-glyphs.nam](https://github.com/google/fonts/blob/master/tools/encodings/latin_unique-glyphs.nam)

**Comment by s-a** [comment]
@davelab6 thanks for reporting the problems.  
As you already noticed I am very far away from professional font artist :).  
This font aims to display numbers only. So while  it uses very limited lines to display numbers from 0 to 9 I see no way to support all signs and it is not  intended for that.

I believe this ticket regards to https://github.com/s-a/fonts/blob/master/apache/digitalnumbers/METADATA.json#L18 `subsets`. Is this necessary? or is a subset of subset possible?

**Comment by davelab6** [comment]
Basic Latin is required for gf...

Since this font is based on the simple grid, I think it's possible to have
fun trying to make letters fit even though you are modest about your design
skills :)

May need to add diagonal pieces to the LCD grid ;)
