### ISSUE TITLE
D and O are indistinguishable

### ISSUE THREAD

**Issue by ctrlcctrlv** [s-a/digital-numbers-font#11]
![dodo](https://cloud.githubusercontent.com/assets/838783/8619310/896fbdf2-2748-11e5-8643-be127a5b8d04.png)

**Comment by davelab6** [comment]
I'm not sure this should be fixed, that is how things look on these displays :)

**Comment by s-a** [comment]
Yes. This font was made to mimic displays of hardware. As the name says mainly numbers. We have here an environment such like a pocket calculator :smile_cat: So at this point it works as expected.

**Comment by ctrlcctrlv** [comment]
I don't think that's fair. 

Some glyphs are a fourteen segment display (W) while others are a seven segment display (DODO).

Fourteen segment display:
![14](https://upload.wikimedia.org/wikipedia/en/0/0a/14_Segment_LCD_characters.jpg)

Seven segment display:
![7](https://upload.wikimedia.org/wikipedia/commons/9/97/7-segments_Indicator.gif)

What I am saying is, make up your mind :smile:. If it's a 14 or 16 segment display, my suggestion is more than possible.

Also I was going to open a separate issue for this, but I think you'd just close it given how...non-receptive you were to this one :wink: but 

Your X and Y are impossible. They need dividers between them to be believable, currently they aren't possible on any type of display, unless it was made just to show an X (and another just to show a Y and nothing else). ![xy](https://cloud.githubusercontent.com/assets/838783/8632062/3ce83a0c-27bd-11e5-8229-e1661b9ec77c.png)

**Comment by ctrlcctrlv** [comment]
I decided to just work on my own 14 segment font rather than bother you.

![lcd](https://cloud.githubusercontent.com/assets/838783/8632873/37794a7a-27e0-11e5-9254-9e82efb16824.png)

**Comment by davelab6** [comment]
Ah yes, a lowercase d would be nice :)

**Comment by ctrlcctrlv** [comment]
I've gotten quite far with my own...

![lcd1](https://cloud.githubusercontent.com/assets/838783/8634271/e78b221e-2824-11e5-887e-f3478fa24213.png)

I'm now considering how to handle umlauts, acute accents and the like. 

I don't want to break with my style, which is to not break the 14-segment in any situation, so I might have to pretend that for those characters there was an extra 4 segments installed like this...

![sel](https://cloud.githubusercontent.com/assets/838783/8634278/53ee594e-2825-11e5-87d0-cdae5f9ee68f.png)

The good thing is I found a configuration like this online so it's not completely unbelievable, as in would never happen on a real LCD.

![111segment](https://cloud.githubusercontent.com/assets/838783/8634291/d4264518-2825-11e5-98eb-b66726930a3d.gif)

This allows me to have dieresis, grave, acute, circumflex and ring (turn on only one dieresis)...however no tidle. I think I can make alternate glyphs for the glyphs that have tildes above them and just put a line above them.

**Comment by ctrlcctrlv** [comment]
Also a sample :D

![sample](https://cloud.githubusercontent.com/assets/838783/8634298/417deec2-2826-11e5-8e61-21c85d4fab93.png)

**Comment by davelab6** [comment]
Love it! Will you make this ofl too?

**Comment by ctrlcctrlv** [comment]
Yes.

I plan on:

Two families, 14 Segment and 7 Segment. I was going to do 16 Segment as well but decided that I wouldn't actually meaningfully use the freedom provided by top and bottom being divided in half.

Each will have:
- Condensed
- Italic
- Italic Condensed

There probably won't be bold.

14 will be the most complete. 7 will be missing quite a bit due to how many glyps are impossible with it. For example...k, m, v, w, x. But it will have at least the digits. I mostly needed the 14 as I wrote.

Variations are easy just by applying FontForge's transformations so why not :wink:

**Comment by ctrlcctrlv** [comment]
I finished ISO 8859-1 in my way.

I decided it would be necessary for extra segments above and below to support European type...so I gave in and created this thing.

![lel](https://cloud.githubusercontent.com/assets/838783/8637045/653a6eda-28b2-11e5-8c80-7299850ad811.png)

I then deleted segments as usual for creating the rest of the letters.

![iso](https://cloud.githubusercontent.com/assets/838783/8637053/c37d42e2-28b2-11e5-9c84-816646840ad4.png)
![spanish2](https://cloud.githubusercontent.com/assets/838783/8637055/c8556d4e-28b2-11e5-9419-969eb6da9ae4.png)
![spanish1](https://cloud.githubusercontent.com/assets/838783/8637056/c89d40a6-28b2-11e5-8f01-3998764ea884.png)
![german](https://cloud.githubusercontent.com/assets/838783/8637057/c8a5a066-28b2-11e5-833e-cf7b9bfe69f2.png)
![br](https://cloud.githubusercontent.com/assets/838783/8637062/eb431496-28b2-11e5-9054-300e93300385.png)

After I decide exactly how much skewed italic will be and how much narrower condensed will be I'll make Github release. 

Overall I am quite happy with how it came out. :) Thank you for "notfixing" this and giving me something to do.

**Comment by davelab6** [comment]
Awesome!! 

Please check https://github.com/google/fonts/blob/master/CONTRIBUTING.md#font-requirements including the glyph set :)
