### ISSUE TITLE
Correct Directions; Remove Overlaps

### ISSUE THREAD

**Issue by davelab6** [s-a/digital-numbers-font#6]
In https://github.com/s-a/digital-numbers-font/blob/gh-pages/build/script.pe you need to correct directions and remove overlaps, or this happens:

![screen shot 2015-06-05 at 5 34 42 pm](https://cloud.githubusercontent.com/assets/261579/8015831/47170c80-0baa-11e5-8463-815d39226af2.png)
![screen shot 2015-06-05 at 5 34 36 pm](https://cloud.githubusercontent.com/assets/261579/8015833/471b0470-0baa-11e5-841b-c2bee6bec80f.png)

![screen shot 2015-06-05 at 5 34 27 pm](https://cloud.githubusercontent.com/assets/261579/8015834/471cf712-0baa-11e5-81e4-68905c1640b7.png)
![screen shot 2015-06-05 at 5 34 29 pm](https://cloud.githubusercontent.com/assets/261579/8015832/471af246-0baa-11e5-9568-8f62b75dd255.png)

I suggest using python to make a `build.py` like this (written into the issue without testing :)

``` py
import fontforge
font = fontforge.open("../src/digital-numbers.sfd")
for glyph in font.glyphs():
    glyph.round()
    glyph.correctDirection()
    glyph.removeOverlap()
    glyph.addExtrema()
    glyph.simplify()
formats = ['sa-digital-number.ttf', 'sa-digital-number.svg', 'sa-digital-number.woff', 'sa-digital-number.eot']
for file in formats:
    font.generate(file, flags=("round", "dummy-dsig"))
```

**Comment by s-a** [comment]
@davelab6 TY for the pull requests. 
When I designed those letters I accepted these overlaps as part of the art :), but 
I added your [build.py](https://github.com/s-a/digital-numbers-font/blob/gh-pages/build/build.py) build script. Not bad that you hacked this from scratch without a test. It worked from the first time. :)

But there are two problems that have nothing to do with the script.

`glyph.correctDirection()` will breake some letters for example `k` (not tested them all)

![image](https://cloud.githubusercontent.com/assets/1270662/8018914/05fec56e-0c34-11e5-969b-ef703f717285.png)

`glyph.removeOverlap()` has no effect.  

I tried both commands within the fontforge GUI. I am using the latest release from github. 

```
C:\git\digital-numbers-font\build>fontforge --v
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 09:31 AWST  1-May-2015-ML-TtfDb-D.
 Based on source from git with hash: 1aba9cbdf300dc7dcb40eba5e2f5c31f40a37818
no xdefs_filename!
TESTING: getPixmapDir:c:/Program Files/FontForgeBuilds/share/fontforge/pixmaps
TESTING: getShareDir:c:/Program Files/FontForgeBuilds/share/fontforge
TESTING: GResourceProgramDir:c:/Program Files/FontForgeBuilds/bin
trying default theme:c:/Program Files/FontForgeBuilds/share/fontforge/pixmaps/resources
fontforge 09:31 AWST  1-May-2015
libfontforge 20150501
```

**Comment by adrientetar** [comment]
I think you must try to do contour.correctDirection() for each contour. FontForge cannot correct direction of a glyph that has contours of different directions. 
If you do that then removeOverlap() should work.

**Comment by s-a** [comment]
I think this was a problem with some letters. I created them new from scratch within fontforge.
